[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

build_flags =
    -DSSID_AP=\"ESP32_LOCAL_duc\"
    -DPASS_AP=\"12345678\"
    -DELEGANTOTA_USE_ASYNC_WEBSERVER=1

; 1. LỆNH CẤM VẬN THƯ VIỆN RÁC GÂY LỖI
lib_ignore = 
    RPAsyncTCP
    ESPAsyncTCP

; 2. TẢI ĐÚNG THƯ VIỆN ASYNCTCP CHUẨN CHO ESP32
lib_deps =
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor